### ISSUE TITLE
[Azure] ACI Provider requires Proper Retry and Back-off Logic when Calling ARM

### ISSUE THREAD

**Issue by robbiezhang** [virtual-kubelet/virtual-kubelet#105]
---
### Issue Details
ACI provider doesn't retry properly on ARM failure, and doesn't regard the 429 status code from ARM. It will cause throttling easily.

**Comment by yolo3301** [comment]
As a first step, should we migrate to use the official azure go sdk? It seems has better error type defined? https://github.com/Azure/azure-sdk-for-go/blob/master/services/containerinstance/mgmt/2018-02-01-preview/containerinstance/containergroups.go

**Comment by robbiezhang** [comment]
This is a good idea. We explored it before and found 2 issues:
1. The SDK has it's own release schedule, and is not always up-to-date.
2. All the properties are defined as pointers. They are inconvenient to use.

**Comment by noelbundick** [comment]
Does the scope of this issue include not retrying at all on all types of failures that will never succeed? ex: trying to run pods with the ACI provider that have not specified a CPU/memory request

**Comment by robbiezhang** [comment]
@noelbundick, this is a good point. I think the current VK already covered the missing resource request issue.

**Comment by robbiezhang** [comment]
@noelbundick, I guess the retry happened in the k8s deployment in your case. The pod is marked as "ProviderFailed" if the resource request is not specified. So, the deployment will spin up another pod immediately, which still fails. From the VK side, we can fix the particular issue by fill the required fields with a default value.

**Comment by noelbundick** [comment]
@robbiezhang yeah, it was a deployment. Makes sense that it could have been deployment causing VK to try a bunch of different pods instead of VK retrying ARM calls on the same pod. I'd have to spin something back up again to verify.

I'd be happy with some sensible defaults that are well-documented - maybe ones that match the Azure CLI defaults - and/or better validation in the ACI provider to just skip the ARM call when we know it's going to fail in advance.
