### ISSUE TITLE
Feature: Implement GRPC out-of-tree provider support 

### ISSUE THREAD

**Issue by corrieb** [virtual-kubelet/virtual-kubelet#160]
** Alpha Release **

We need to enable Providers to be hosted out of tree. The mechanism by which this will work is to replace the existing compile-time dependency on Providers to a GRPC plug-in mechanism.

**Comment by asrivas-vmw** [comment]
@rbitia You can assign this issue to me.

**Comment by asrivas-vmw** [comment]
I spent some time researching this last week and it looks like we will need to either pull in all K8s types as part of the protobuf definition, or limit the provider interface to something that is a subset of a pod spec. The latter sounds undesirable so I'm looking for ways, if folks are aware of any, to pull in all of the podspec into a protobuf without having to re-define each and every field explicitly and then maintaining / extending this protobuf as the pod spec changes over time. Any ideas?

**Comment by ofiliz** [comment]
I had also proposed the approach @sflxn described above during the VK offsite. This is similar to what CNI does: Build functionality as a library that plugins can link to.

I don't think having "many variants of the virtual-kubelet floating around" is a problem. That should actually be the desired behavior. If I don't have to distribute other provider logic in my own Fargate provider, I don't have to deal with those providers' security vulnerabilities, carry their libraries that I don't use, etc.

**Comment by sflxn** [comment]
Per our conversation at the VK weekly meeting on 5/23, we all agreed to go ahead and do the library approach.  We can always move back to the independent binaries communicating with GRPC later.

**Comment by asrivas-vmw** [comment]
Agreed, that does sound like the better short term approach for sure rather than redefining all of the Kubenetes types and interfaces as part of the protobuf. I'm happy to look into this when I get a chance, but if anyone is interested in getting this done soon, let me know and I can re-assign it.

**Comment by asrivas-vmw** [comment]
There is an easier way to do this, which is to let VK be the main process but let the providers be dynamically loadable Go plugins[1]. All the providers can be built as plugins and on invocation of VK, one of them can be chosen based on a string parameter it takes in when it starts up. That way we don't need to librarify VK but we still get the benefits of out of tree support. 

[1] https://medium.com/learning-the-go-programming-language/writing-modular-go-programs-with-plugins-ec46381ee1a9

**Comment by rbitia** [comment]
for the above proposal users would need to know/have: 
Go 1.10 
Only works on Linux 
other options: 
1. what cni does: Publish plugins and provide a call with the object and a standard specification
2. grpc: pattern for cloud providers-> defining a protobuf was difficult and it was pulling in all of k8s
3. convert VK into a shared library  


**Investigate the plugin model for Go**

**Comment by asrivas-vmw** [comment]
Initial investigations with Go's plugin model have not been very promising. It turns out that there are a number of problems with the current model for how vendored dependencies are managed in plugins and the main binary that make the current plugin model quite untenable. Some of these are being tracked in github issues within the golang community:

https://github.com/golang/go/issues/20481
https://github.com/golang/go/issues/18827

This also seems to be the reason why a large number of other golang projects have decided to not go forward with this approach for managing plugins in their projects. One example from the Jaegar community is documented in this issue:
https://github.com/jaegertracing/jaeger/issues/422

In light of this, I came across one other potential solution that might work, which is based on net/rpc developed by hashicorp:
https://github.com/hashicorp/go-plugin

This looks a lot more promising than anything else at the moment. These plugins do not run in process though, and are fork-exec'd by the main binary and communicate over a RPC channel which can be configured to run over unix domain sockets or localhost tcp. The good part about this approach is that all the work necessary to define protobufs etc between the main binary and plugin are automatically taken care of by the framework itself. This framework is also being used heavily in the Go community, projects like Packer, Terraform have been using this since Go 1.5 so there is no specific or obscure language features required for utilizing this.

I will investigate this further.

**Comment by zootalures** [comment]
gRPC extension via unix sockets  feel like norm/future trajectory for Kube generally  - (e.g. CSI https://github.com/container-storage-interface/spec/blob/master/spec.md, Device plugins: https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/ etc)  while there is a alot of investment in getting the machinary working it pays off in future in consistency,familiarity, good x-language support. 

hashicorp plugins add some things on top of that but they are/were originally focussed on CLI  extension rather than service extension and some of that is still prevalent - I wonder if the trade-off of speed/less legwork is worth it for the moderate baggage they add . They are also MPL 2.0 which may be problematic for some folks.

**Comment by cpuguy83** [comment]
Its seems like providers all package their own VK. Do we need to use plugins here rather than taking the library approach?

**Comment by asrivas-vmw** [comment]
@zootalures brings up a good point regarding licensing, that is definitely something to stay clear of. Since Go statically links all its dependencies, I would assume that more restrictive licenses could end up tainting the binary. 

@cpuguy83 I guess we are back to the VK as a library approach then.

**Comment by cpuguy83** [comment]
I opened https://github.com/virtual-kubelet/virtual-kubelet/issues/348 to discuss some of the changes I see that need to be made to the code base.

**Comment by pires** [comment]
My opinion is that scoping VK as a library (building block), any provider can then import it, initialize it, run. By doing so, all problems related to out-of-tree simply go away.

Be careful when mentioning CSI and CNI and related because these own all the types used in their APIs. These APIs don't care about Kubernetes types. And as someone said above, VK does pass Kubernetes types to the provider, which means the gRPC service spec would have to account for that too, i.e. import all the protos.

**Comment by rbitia** [comment]
Closing as this was an earlier discussion and we are thinking of new ways to implement these concepts.
