### ISSUE TITLE
Feature: External volume support

### ISSUE THREAD

**Issue by corrieb** [virtual-kubelet/virtual-kubelet#167]
**Alpha Release**

Virtual Kubelet already handles any volumes that are host-based: emptyDir, secrets, configmaps etc. However a volume that requires external storage to be provisioned, such as a block device, is currently not supported.

There are two key pieces of information in order to provide this support (1) The binding between the pod and a volume and (2) The lifecycle management of the volume itself. The binding is expressed explicitly in the Pod Spec, which is already provided to CreatePod(). So the question of how the Volume is bound to the Pod is Provider-specific.

That leaves simply the need to be able to express Volume lifecycle management to the Provider in terms of Create / Delete. Create will need to take a bunch of metadata and policy, such as size. For most providers, this will simply mean passing data to the Cloud Provider to create block devices. 

We should investigate NFS as part of this feature - decide if that's in or out of scope.

**Comment by sflxn** [comment]
I have an initial design proposal awaiting feedback from internal people.  I hope to present that at the next nodeless architecture meeting.

**Comment by rbitia** [comment]
We should add a watch on PVs and PVCs and providers can listen to the watch if they want. We can use the CRI provider to implement this first.

**Comment by rbitia** [comment]
This doesn't effect the interface and is just an addition so we've removed it from the 1.0 milestone.

**Comment by pires** [comment]
AFAIK in Kubernetes, the `PersistentVolume` creation/deletion, based on `PersistentVolumeClaim`, is the responsibility of a _provisioner_ defined as a `StorageClass`, which in our case would most likely be the [external-provisioner](https://github.com/kubernetes-csi/external-provisioner). The provisioner is the one doing the CSI talk to driver(s) that are then responsible of creating/deleting the actual volumes.

In my understanding, the problem lies with VK providers integrating well with existing CSI drivers integration, and not with VK implementing the [Device Plugin registration](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#device-plugin-registration) which the [CSI Node registrar](https://github.com/kubernetes-csi/node-driver-registrar) would use to register CSI drivers. And this is no easy feat.

Honestly, my hunch is this is a moonshot and we will only learn about if/how VK can help providers after a provider implements the functionality and shares lessons learned.

**Comment by cpuguy83** [comment]
Agreed. The best way to do this is to have a provider support it then figure out how we can abstract that.

**Comment by abhideodhar-coder** [comment]
How to enable existing CSI drivers to work with VK? 
Does VK implement the Device plugin registration and Node registrar functions to enable the VK provider? I briefly looked at the VK code and couldn't find the PluginWatcher implementation which watches the plugin socket file creation and enables CSI driver to register with VK. Is this planned?

**Comment by cpuguy83** [comment]
@abhideodhar-coder The only things VK provides today is tooling to help with spinning up a service that satisfies the API's needed to operate a node on k8s. CSI is implementation specific (to Kubelet) and there is nothing in VK that deals with it.

**Comment by cpuguy83** [comment]
Closing since this is not something we can support in the VK core.
Each provider will need to figure out how to support volumes for their own provider because it is provider specific.
We may be able to come up with something like a generic way to support, for instance, CSI that providers could use however the core VK runtime cannot directly handle volumes.
