### ISSUE TITLE
Pod not rescheduled if corresponding Fargate task is stopped manually

### ISSUE THREAD

**Issue by gamer22026** [virtual-kubelet/virtual-kubelet#208]
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)
**AWS Fargate**
Version (e.g. 0.1, 0.2-beta)
**v0.3**
K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
**1.8.12 via kops**
Install Method (e.g. Helm Chart, )
**manual**
### Issue Details
Killing a Fargate task via ECS dashboard that was started by a kubernetes deployment leaves pod in Pending mode. Would expect the deployment to reschedule the Fargate task (just like killing a pod in kubernetes triggers a redeploy).  Current workaround is to restart the virtual-kubelet which then correctly reschedules the pod) 
### Repo Steps
Any deployment via Fargate provider. Stop running task from ECS dashboard. Observe pod remains in pending state until virtual-kubelet is restarted.

**Comment by ofiliz** [comment]
Hi @gamer22026,
Sorry for the delayed response. You are right that the Fargate task needs to be rescheduled in this case. I am rethinking the Kubernetes <-> Fargate interaction design at a larger scale, and this issue is a manifestation of a more generic problem. I will update the design, which will also fix this issue.

**Comment by rbitia** [comment]
Closing because this issue is stale!
