### ISSUE TITLE
Failed pods not reconciled

### ISSUE THREAD

**Issue by cpuguy83** [virtual-kubelet/virtual-kubelet#399]
When a pod fails we set the reason "ProviderFailed" but the pod state still says "Pending".
This state never gets reconciled and a pod deployment will be short until the pod is either deleted by the user or it's state updated to Failed.

**Comment by robbiezhang** [comment]
This is in purpose, as marking pod phase to Failed will make the deployment create new pods. 
We assume the provider should handle retry-able errors, and only return non-retry-able ones, for example a spec error, which will never get created.

**Comment by cpuguy83** [comment]
Ok, that makes sense, however this feels like duplicated behavior (which I don't think is implemented) for all providers and I think would require blocking the calling thread for retries.

If we can implement an error type that providers can return we can pull this behavior into core.
Perhaps an error interface like:

```go
type RetryableError interface {
    error
    Retry() time.Duration
}

**Comment by robbiezhang** [comment]
Yup, this is some what's planned to do from a long time.

**Comment by robbiezhang** [comment]
@cpuguy83, will you add the RetryableError in the strongerrors repo?

**Comment by cpuguy83** [comment]
The error from strongerrors would be the `Unavailable` error (https://github.com/cpuguy83/strongerrors/blob/master/defs.go#L29).

We may not need to do communicate the retry time and instead just queue it up to retry in some offset, like 5 minutes.

I think this is just a nice to have for providers that do have details about when we should retry... I think the Azure errors have this info at least.

We can just implement that in this repo, e.g.

```go
type retryable struct {
    cause error
    retryAt time.Time
}

func(r *retryable) Error() string { return e.cause.Error() }
func(r *retryable) Cause() error { return e.cause }
func(r *retryable) RetryAt() time.Time { return r.retryAt }
```

Then in the vk core we would do somsething like

```go
if strongerrors.IsUnavailable(err) {
  retryAt := time.Now().Add(5*time.Mimute)
  if at, ok := retryTime(err); ok {
    retryAt = at
  }
}
```

**Comment by robbiezhang** [comment]
Sounds good. Minor thing: prefer using `retryAfter time.Duration`, which align with the Azure standard.

**Comment by cpuguy83** [comment]
The only reason I used a `time.Time` is the error will return a duration and then I want to tell the caller you can retry after the "current time when we received the error + duration" rather than "time you, the caller, read the error + duration", but it's probably moot.

**Comment by cpuguy83** [comment]
The state of this is a bit better today as we do retry, although the retry logic could definitely be better  (basically it always retries even on user error), and there is a max retries which when hit we end up dropping it.

**Comment by turkenh** [comment]
> This is in purpose, as marking pod phase to Failed will make the deployment create new pods.
We assume the provider should handle retry-able errors, and only return non-retry-able ones, for example a spec error, which will never get created.

@robbiezhang I am confused here. Pod phase is actually not marked as `Failed` but `Pending` which seems not aligned with the purpose you mentioned.

We are also having the same problem mentioned here and I couldn't get why we don't sync pod status back. 
AFAIU, here is what happens:
1. Pod A created for provider X
2. `CreatePod` method provider X is called
3. Some transient error occurs (network error, some conflict etc), and provider returns error for `CreatePod`
4. I see pod status as:

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-30T19:46:13Z"
    status: "True"
    type: PodScheduled
  message: 'something bad happened, please try again'
  phase: Pending
  reason: ProviderFailed
```

5. Virtual Kubelet does a retry and calls `CreatePod` again after a while which is great
6. `CreatePod` succeeds this time and returns no error.
7. NotifyPods called which returns new state of pod
8. [updatePodStatus](https://github.com/virtual-kubelet/virtual-kubelet/blob/b91d892bffd3de16089cdb82f4aaae8c7d17df80/node/pod.go#L201) func called for the pod.
9. It skips status update because of [this line](https://github.com/virtual-kubelet/virtual-kubelet/blob/b91d892bffd3de16089cdb82f4aaae8c7d17df80/node/pod.go#L198).

So, even we have did a retry and succeed, we couldn't sync status back to pod and it stuck as `ProviderFailed` forever. 
I don't think all providers should take care of any errors they return and be responsible for retry given we already have a retry here. 

So the question is, what to do with [this line](https://github.com/virtual-kubelet/virtual-kubelet/blob/b91d892bffd3de16089cdb82f4aaae8c7d17df80/node/pod.go#L198) as it seems to prevent reflecting success of a retry back ?

**Comment by turkenh** [comment]
@cpuguy83 @robbiezhang could you please have a look my PR: https://github.com/virtual-kubelet/virtual-kubelet/pull/898
