### ISSUE TITLE
Dropping events

### ISSUE THREAD

**Issue by cpuguy83** [virtual-kubelet/virtual-kubelet#400]
Pod synchronizer will drop events if there is any kind of error from the provider (including rate limiting).

This is an issue for create because of #399

This is an issue for delete it never ends up getting deleted in the provider.
We could reconcile this occasionally, such as #391 will do, however it would be nice to make sure these get deleted as soon as possible since this can translate into $$$ for users.

**Comment by robbiezhang** [comment]
My $.02:
1. For the delete error, we need to retry since it leaves the k8s control plane, and might not be triggered by new event.
2. For the create error, my idea is that provider need to tell the VK whether it is a retry-able error or not.
The current implementation actually assumes the error from the provider is always non-retry-able. Thus, we don't re-create the pod and forbid the deployment to create new pods by not setting the pod phase to "Failed". And it also assumes that the provider should handle the retry-able error themselves.

**Comment by sargun** [comment]
@cpuguy83 is this still a problem, given we have retries now?

**Comment by cpuguy83** [comment]
Probably not nearly as bad as it once was.
Maybe the best thing to do is to have a hook to notify that "we are dropping this even due to <error> after N retries"

**Comment by pires** [comment]
We do requeues now and we also have the full resync period that will re-trigger events in case we missed some event, ie a key is missing from the queue. I'm going to close this in hopes no one will re-open it because we're still observing it.
