### ISSUE TITLE
Getting VK to 1.0 

### ISSUE THREAD

**Issue by rbitia** [virtual-kubelet/virtual-kubelet#413]
Let's come up with a list of requirements and changes we'd like to implement before getting to a 1.0

**Comment by cpuguy83** [comment]
Just off the top of my head:

1. e2e test suite
2. Refactor provider interfaces (a couple of examples I can come up with that need work)
a. `Exec` implementation is pretty limiting, nice that it re-uses some existing stuff from k8s, but ultimately it makes too many assumptions and is difficult to integrate with.
b. Logs should be an I/O stream all logs get dumped into memory.
c. Providers should not need access to the resource manager
d. Some of the interfaces are questionable in their use case, e.g. `OperatingSystem` (which is passed into the provider already, `NodeDaemonEndpoints` (not generally controlled by the provider), and a few others.
3. Rely more on the (quite good) k8s client instead of hand-crafted things like resource manager.

**Comment by pires** [comment]
I second @cpuguy83's comment above and that's what I'm focusing on too.

I also did a pass on all the open issues and I found the following to be candidate for a GA milestone:

- #34
- #158
- #170
- #210
- #238
- #300
- #304
- #314
- #316
- #321
- #324
- #347
- #348
- #397
- #399
- #400
- #404

But more importantly, I think it's of paramount importance to define the scope for VK. Why? Because looking at most of feature requests, asks on slack, and from some discussions, it seems to me it's not clear whether this is a building block; a gateway to _containers-as-a-service_; a platform (e.g. that handles scheduling predicates such as anti-affinity). If the scope is unclear, I believe it will be hard to commit to a roadmap and prioritize what the project wants to execute/deliver.

**Comment by pires** [comment]
I also suggest when there's agreement on what's going to be 1.0, a github milestone is created to keep track of related issues/PRs.

**Comment by asrivas-vmw** [comment]
>    a. `Exec` implementation is pretty limiting, nice that it re-uses some existing stuff from k8s, but ultimately it makes too many assumptions and is difficult to integrate with.
>    b. Logs should be an I/O stream all logs get dumped into memory.

Opened #423 to track these items.

**Comment by rbitia** [comment]
#34 
#158 & #159
#170
#210 
#304
#314
#316
#321 & #427
____________________________________________
#324
#347
#348
#397
#399
#400
#404
#436

**Comment by cpuguy83** [comment]
This is done!
