### ISSUE TITLE
Virtual Kubelet causes AKS upgrades to fail

### ISSUE THREAD

**Issue by AceHack** [virtual-kubelet/virtual-kubelet#42]
If you install virtual kubelet it will cause AKS upgrade failures

See issue

https://github.com/Azure/AKS/issues/83

**Comment by rbitia** [comment]
I'll test this out and see what's going on here. Thanks!

**Comment by rbitia** [comment]
Alright so upgrading your AKS cluster w/ the ACI Connector installed does work as I just tried it! But the Connector has a bug where any service that's deployed will not be provisioned an IP from the load balancer-> though that issue is being tracked here #41. I'll close this issue for now, unless you have any other issues with upgrade in the context of the Connector.

**Comment by rbitia** [comment]
Closing the issue! 

Thanks!
