### ISSUE TITLE
Support metrics-server v0.3

### ISSUE THREAD

**Issue by cpuguy83** [virtual-kubelet/virtual-kubelet#475]
metrics-server v0.3 seems to only support fetching metrics from the main kubelet interface rather than what v0.2 does (a separate endpoint on an unsecured port).

I've only looked at this while debugging some other issues, so I'm not sure if there is more to do than just adding the endpoints on the main interface.

**Comment by ldx** [comment]
Metrics-server now defaults to the https kubelet server (10250), since the readonly port (10255) has been disabled by default: https://github.com/kubernetes/kubernetes/pull/59666#issuecomment-373829976

You can still enable the readonly port and configure metrics-server in your cluster to use that port without TLS via `--kubelet-port=10255 --deprecated-kubelet-completely-insecure=true`.

@cpuguy83 what do you think of adding the stats summary handler to the https server in node-cli (while also keeping it in the http one)?

**Comment by cpuguy83** [comment]
SGTM

**Comment by DreamRivulet** [comment]
@ldx @cpuguy83 May I know whether there is an ETA for virtual kubelet to support kubelet summary API on 10250? Currently virtual kubelet doesn't support metrics-serverv 0.3 which caused k8s HPA not working for pods on virtual kubelet.

**Comment by ldx** [comment]
@DreamRivulet it's on my todo list, but I don't have an ETA. You can reconfigure metrics-server to use the read-only port as a workaround for now.

**Comment by cpuguy83** [comment]
VK is only a library. You configure listeners.

**Comment by DreamRivulet** [comment]
@ldx  Thanks a lot. We're using the AKS cluster, and it's not possible for us to reconfigure metrics-server. Besides, kubelet is using 10250 port for summary API, if we change metrics-server to use 10255, it will not be able to get metrics from kubelet.

**Comment by cpuguy83** [comment]
I opened https://github.com/virtual-kubelet/node-cli/pull/27 to update this on the cli lib that some projects are using.

It disables the metrics port by default and serves metrics on the main port.
