### ISSUE TITLE
Rebalancing Pods off of Virtual Kubelet

### ISSUE THREAD

**Issue by RehanSaeed** [virtual-kubelet/virtual-kubelet#593]
Azure ACI is more expensive as compared to running pods on an AKS node but AKS nodes take minutes to be created during which time pods are created on Azure ACI. Once all scaling activities are completed, is there some way to rebalance pods, so that Azure ACI pods are stopped and replaced with new pods on AKS nodes to save money?

Is this something that the `preferredDuringSchedulingPreferredDuringExecution` [pod affinity rule](https://kubernetes.io/docs/concepts/configuration/assign-pod-node) that is not yet implemented in Kubernetes could solve or is there another method?

**Comment by cpuguy83** [comment]
Rebalancing is the work of the scheduler and not applicable to virtual-kubelet.
The way to force it to happen would indeed be to kill the pods running on ACI so that the pod gets rescheduled.
Maybe adding the VK node taint when you want it to use ACI and then removing when you don't is enough to trigger this?

**Comment by RehanSaeed** [comment]
I think most users of ACI would want to know how to trigger adding/removing the taint as you suggest automatically.

**Comment by cpuguy83** [comment]
I couldn't really tell you how to do it automatically. The other option would be not to use the taint and delete the pods you want re-balanced.

Closing since this isn't really an issue and not something we can really control here.
