### ISSUE TITLE
Cut Release?

### ISSUE THREAD

**Issue by sargun** [virtual-kubelet/virtual-kubelet#778]
We've made a backward-incompatible change in the VK. We should cut a major release.

**Comment by cpuguy83** [comment]
Why?

**Comment by cpuguy83** [comment]
btw, I have a milestone to track the next release here: https://github.com/virtual-kubelet/virtual-kubelet/milestone/4

Target date is semi-strawman for Oct 23.

**Comment by sargun** [comment]
It seems like go modules really want you to do semver. See: https://github.com/golang/go/wiki/Modules#semantic-import-versioning

Would v1.2.0 indicate a backwards incompatible release?

**Comment by cpuguy83** [comment]
I don't think we need to make a release only because of the change. I'd like to group things together.

As to whether or not it's backwards incompatible, that's hard to say. VK still works the same we just added a feature to the interface.
Of course this means anyone who wants to upgrade will need to make changes to their code.

We may also in the meantime realize we didn't need to make the change and revert?
