### ISSUE TITLE
Proposal for handling v1 Leases

### ISSUE THREAD

**Issue by sargun** [virtual-kubelet/virtual-kubelet#887]
I propose we adopt v1 leases, and we adopt them how Kubelet uses them, as a reachability check and not a healthcheck. Kubernetes 1.17 is now the [oldest supported version](https://kubernetes.io/docs/setup/release/version-skew-policy/#:~:text=Supported%20versions&text=The%20Kubernetes%20project%20maintains%20release,9%20months%20of%20patch%20support) of Kubernetes. Given this, 1.17 clusters should have node leases on as default and use them for reachability checks. Given this, I think we should make the following changes:

- [ ] Remove v1beta1 leases completely
- [ ] Add v1 leases based on the approach highlighted in https://github.com/virtual-kubelet/virtual-kubelet/pull/880/files, but them on by default, rather than behind an option
- [ ] Make lease renewal unrelated to provider ping
- [ ] Allow a condition to be set as a result of provider ping. This can either be "change this specific condition name to false", "Set the ProviderReady condition to false", or "set Ready to false" [and even if Ready is set to True in the node status update from the provider, rest it to false].
- [ ] Making automagically updating lastheartbeat time optional

**Comment by pires** [comment]
+1 breaking w/ node updates to move to Leases v1.

I'm fine w/ a minor release that breaks with certain Kubernetes versions from the past. Having a major release is quite painful when dealing w/ Go modules. We should announce it as a breaking change in the release notes.
Also, it's up to providers to import the newer modules or not so breaking with older versions of Kubernetes is really an option of provider owners, right?

**Comment by sargun** [comment]
@cpuguy83 suggested that we introduce a NodeControllerV2 that would have this behaviour.

I think my primary worry is either we end up with a bunch of "copy pasta" between the v1 and v2 implementations, or there will be a bunch of shared code and testing will become harder. I also think that doubling our CI/CD time doesn't see super appealing.

**Comment by pires** [comment]
I agree w/ @sargun.

**Comment by cpuguy83** [comment]
I would like to be able to support v1.16 at least still.

@sargun mentioned issues with the existing automatic fallback behavior where if we can't create a lease (assumming the feature is not enabled) we just do node status updates. VK ends up in this behavior where it always hits the fallback behavior due to issues on the cluster.

Splitting up these into separate controllers instead of the single loop seems like a good step here and does seem like it would prevent the automatic fallback.

Given the beta declaration of lease support, it seems fine to drop the v1beta1 lease behavior.
Making sure that compilation fails for anyone using v1beta1 leases seems ideal.

Maybe we can have a special value (e.g. -1) to explicitly disable the lease controller (I suppose we could do this for all of the controllers)?

**Comment by sargun** [comment]
@cpuguy83 So you're fine deprecating the autofallback behaviour?

**Comment by cpuguy83** [comment]
@sargun Yes, absolutely.

**Comment by cpuguy83** [comment]
V1 leases are merged, closing.
